[package]
name = "fishfight"
version = "0.4.1"
description = "A tactical 2D shooter"
authors = ["Fish Fight Contributors"]
license = "MIT OR Apache-2.0"
edition = "2021"

[target.'cfg(target_arch = "wasm32")'.lib]
crate-type = ["cdylib"]

[workspace]
members = ["core", "core/macro", "physics-platformer"]

[profile.dev.package."*"]
opt-level = 3

[dependencies]
ff_core = { path = "./core", version = "0.4.1", package = "fishfight-core", default-features = false, features = ["internal-backend"] }
# ff_core = { path = "./core", version = "0.4.1", package = "fishfight-core" }
# ultimate = { path = "../FishFight-ultimate/client", package = "fishfight-ultimate-client", optional = true }
fishsticks = { version = "0.2.0", default-features = false, features = ["gilrs"] }
macroquad-platformer = { path = "physics-platformer" }
hecs = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", default-features = false, features = ["serde-serialize"] }
js-sys = { version = "0.3", default-features = false }

[target.'cfg(all(debug_assertions, target_arch = "wasm32"))'.dependencies]
console_error_panic_hook = "0.1.5"

[patch.crates-io]
fishsticks = { git = "https://github.com/fishfight/fishsticks", branch = "main", default-features = false, features = ["gilrs"] }