[video]
max-fps = 120
high-dpi = false
vsync = false

[window]
mode = "windowed"
width = 955
height = 600

[audio]
master-volume = 100
sound-effect-volume = 100
music-volume = 100

[input.keyboard-primary]
left = "Left"
right = "Right"
fire = "L"
jump = "Up"
pickup = "K"
crouch = "Down"
slide = "RightControl"

[input.keyboard-secondary]
left = "A"
right = "D"
fire = "LeftControl"
jump = "W"
pickup = "C"
crouch = "S"
slide = "F"

[[input.gamepads]]
id = 0
fire = "A"
jump = "X"
pickup = "B"
slide = "Y"
