[package]
name = "fishfight-core"
version = "0.4.1"
authors = ["Fish Fight Contributors"]
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = ["internal-backend", "platformer-physics"]
internal-backend = ["winit", "winit_input_helper", "tokio", "glam", "glow"]
macroquad-backend = ["macroquad", "ff-particles"]
platformer-physics = []

[dependencies]
macros = { path = "./macro", version = "0.4.1", package = "fishfight-core-macros" }
fishsticks = { version = "0.2", default-features = false, features = ["gilrs"] }
macroquad = { version = "0.3.13", optional = true }
ff-particles = { version = "0.1", features = ["serde"], optional = true }
glow = { version = "0.11.2", optional = true }
winit = { version = "0.26.1", features = ["serde"], optional = true }
winit_input_helper = { version = "0.11.1", optional = true }
# tokio = { version = "1.17.0", features = ["macros", "sync", "rt"], optional = true }
tokio = { version = "1.17.0", features = ["sync", "macros", "rt-multi-thread"], optional = true }
glam = { version = "0.20.2", features = ["scalar-math", "serde"], optional = true }
quad-rand = "0.2.1"
quad-snd = "0.2"
hecs = "0.7.1"
serde = { version = "1.0.136", package = "serde", features = ["derive"] }
serde_json = { version = "1.0.79" }
toml = "0.5.8"
cfg-if = "1.0.0"
num-traits = "0.2.14"
async-trait = "0.1.52"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.5", features = ["js"] }
wasm-bindgen = { version = "0.2.79", default-features = false, features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.29"
js-sys = { version = "0.3.56", default-features = false }

[patch.crates-io]
fishsticks = { git = "https://github.com/fishfight/fishsticks", branch = "main", default-features = false, features = ["gilrs"] }
